global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'finance-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:3000']

  - job_name: 'analytics-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:3001']
