server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: finance-logs
    static_configs:
      - targets: ['localhost']
        labels:
          job: finance-service
          app: finance
          __path__: /var/log/finance/*.log
  - job_name: analytics-logs
    static_configs:
      - targets: ['localhost']
        labels:
          job: analytics-service
          app: analytics
          __path__: /var/log/analytics/*.log
